### PR TITLE
Resolve: Inconsistent sort for "Installed as dependency for"

### LINKED ISSUE #63: Inconsistent sort for "Installed as dependency for"
### Environment

*   PIP Chill version: 1.0.1
*   Python version: 3.10.6
*   Operating System: WSL

### Description

The "Installed as dependency for" is not sorted consistently, resulting in unnecessary diffs like:
```
-# python-dateutil==2.8.2 # Installed as dependency for matplotlib, pandas
+# python-dateutil==2.8.2 # Installed as dependency for pandas, matplotlib
```
Ideally these would be sorted (alphabetically?) so that the output is more consistent.

### What I Did

```sh
pip-chill --verbose
```

### PR DESCRIPTION
**Pull request by kjwpaulson**
Resolves #63

### CODE REVIEW

**Comment by rbanffy** [comment]
I probably should have added this recommendation to the CONTRIBUTING file, but it's better if you rebase your commits off the develop branch.

Also, please, add your name to the AUTHORS file.

**Comment by kjwpaulson** [comment]
@rbanffy I think I've made the required adjustments, let me know if it's not correct thanks!

**Review by rbanffy — APPROVED** [review]
LGTM

**Comment by rbanffy** [comment]
Thank you! I'll make a release soon (tons of goodies in the develop branch that need to go into master, and yours goes as well)

**Pull request merged**
